### ISSUE TITLE
wrong

### ISSUE THREAD

**Issue by ghost** [dgryski/go-idea#2]
hi,
1.
your implementation is ok, but wrong
if i have all FF's (hex) for key and plain text its CORRECT
if i have
"00000000020000000000000000000000" - for key
"0000000000000000" - for plain text
its FAILS
1. use all tests from file and you will see 
   https://www.cosic.esat.kuleuven.be/nessie/testvectors/bc/idea/Idea-128-64.verified.test-vectors
2. https://bitbucket.org/mihailp/tankfeeder/src/fa2b4b0c2851337c8e505a5c04389401fa306db4/crypto/idea.l?at=default&fileviewer=file-view-default

**Comment by dgryski** [comment]
Wow, thanks for finding that.   I confirm that running the full test vectors causes my code to fail.  I'll look into this tonight and will get a patch out today.

**Comment by ghost** [comment]
the problem around swap x2 and x3 inside loop and-or last round
